#!perl

=head1 NAME

rrd_fetch_helper - 

=head1 SYNOPSIS

rrd_fetch_helper -a <action> ...

rrd_fetch_helper --help [B<-a> <action>]

rrd_fetch_helper -a list_actions

=head1 DESCRIPTION


=head1 FLAGS


=cut

use strict;
use warnings;
use Getopt::Long qw(GetOptions);
use Pod::Usage   qw( pod2usage );
use RRD::Fetch::Helper;
use Pod::Find qw(pod_where);

sub main::VERSION_MESSAGE {
	print 'rrd_fetch_helper v. ' . $RRD::Fetch::Helper::VERSION . "\n";
}

my $help;
my $version;
my $action;
Getopt::Long::Configure('no_ignore_case');
Getopt::Long::Configure('bundling');
use Getopt::Long qw(:config pass_through);
GetOptions(
	'version' => \$version,
	'v'       => \$version,
	'help'    => \$help,
	'h'       => \$help,
	'a=s' => \$action,
);

if ($version) {
	&VERSION_MESSAGE;
	exit 255;
}

if ($help) {
	&VERSION_MESSAGE;

	print '

-a <action>       The action to perform.

';

	if ( !defined($action) ) {
		print 'For help on a specific topic use --help with the specified action in question.

For a list of actions use the action list_actions
';
		exit 0;
	}

	print "Action specific help... \n\n";
	pod2usage(
		-input   => pod_where( { -inc => 1 }, 'RRD::Fetch::Helper::' . $action, ),
		-verbose => 99,
		-output  => \*STDOUT
	);

	exit 0;
} ## end if ($help)

my $rrd_fetch_helper=RRD::Fetch::Helper->new;
$rrd_fetch_helper->run('action'=>$action);
