#!perl

=head1 NAME

rrd_fetch_helper - 

=head1 SYNOPSIS

rrd_fetch_helper -a <action> ...

rrd_fetch_helper --help [B<-a> <action>] [B<-j>] <action args>

rrd_fetch_helper -a list_actions

rrd_fetch_helper --help/-h

rrd_fetch_helper --version/-v

=head1 DESCRIPTION

Calls various RRD::Fetch::Helper modules.

=head1 FLAGS

=head2 -a <action>

The helper module to call.

If combined with --help help info for that action is displayed.

=head2 -j

Print the data returned from the action as JSON instead of what ever it specifies for the output.

=head2 --help/-h

Print the help info.

If combined with -a <action>, it prints the help info for info
for the module in question.

=head2 --version/-v

Print the version info.

=cut

use strict;
use warnings;
use Getopt::Long       qw(GetOptions);
use Pod::Usage         qw( pod2usage );
use RRD::Fetch::Helper ();
use Pod::Find          qw(pod_where);

sub main::VERSION_MESSAGE {
	print 'rrd_fetch_helper v. ' . $RRD::Fetch::Helper::VERSION . "\n";
}

my $help;
my $version;
my $action;
my $as_json;
Getopt::Long::Configure('no_ignore_case');
Getopt::Long::Configure('bundling');
Getopt::Long::Configure('pass_through');
GetOptions(
	'version' => \$version,
	'v'       => \$version,
	'help'    => \$help,
	'h'       => \$help,
	'a=s'     => \$action,
	'j'       => \$as_json,
);

if ($version) {
	&VERSION_MESSAGE;
	exit 255;
}

if ($help) {
	&VERSION_MESSAGE;

	if ( !defined($action) ) {
		pod2usage( -exitval => 255, -verbose => 2, -output => \*STDOUT, );
	}

	print "Action specific help... \n\n";
	pod2usage(
		-input   => pod_where( { -inc => 1 }, 'RRD::Fetch::Helper::' . $action, ),
		-verbose => 99,
		-output  => \*STDOUT
	);

	exit 255;
} ## end if ($help)

my $rrd_fetch_helper = RRD::Fetch::Helper->new;
my $returned         = $rrd_fetch_helper->run( 'action' => $action );

if ($as_json) {
	print JSON->new->allow_nonref->canonical(1)->encode($returned);
	exit 0;
}
print $returned->{'output'};

